### ISSUE TITLE
EPIC: As an Open Data Hub manager I want a web component that generates the Open Data Hub Schedule by taking the data from the Open Data Hub APIs

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/opendatahub-website#186]
For the Open Data Hub Day 2024 we will integrate in the open data hub website a Web Component that automatically creates the Schedule by getting the data from the Open Data Hub APIs

ToDo list
- [ ] Update the Open Data Hub APIs (EventShort and/or Event) Linked to the issue: https://github.com/noi-techpark/odh-tourism/issues/328
- [ ] Develop the Event Schedule WebComponent
- [ ] Integrate the Event Schedule WebComponent in the Open Data Hub Websitte (Event section)

Deadline: 31/01/2024

**Comment by sseppi** [comment]
To plan the development of the web component we will need to have at least in testing the changes on the API that are defined in a dedicated issue:

https://github.com/noi-techpark/odh-tourism/issues/328
